const wordList = [
  { en: 'hello', zh: '你好', grade: '1' },
  { en: 'hi', zh: '嗨', grade: '1' },
  { en: 'bye', zh: '再见', grade: '1' },
  { en: 'teacher', zh: '老师', grade: '1' },
  { en: 'student', zh: '学生', grade: '1' },
  { en: 'school', zh: '学校', grade: '1' },
  { en: 'book', zh: '书', grade: '1' },
  { en: 'pencil', zh: '铅笔', grade: '1' },
  { en: 'bag', zh: '书包', grade: '1' },
  { en: 'desk', zh: '课桌', grade: '1' },
  { en: 'chair', zh: '椅子', grade: '1' },
  { en: 'friend', zh: '朋友', grade: '1' },
  { en: 'name', zh: '名字', grade: '1' },
  { en: 'family', zh: '家庭', grade: '1' },
  { en: 'father', zh: '父亲', grade: '1' },
  { en: 'mother', zh: '母亲', grade: '1' },
  { en: 'brother', zh: '兄弟', grade: '1' },
  { en: 'sister', zh: '姐妹', grade: '1' },
  { en: 'baby', zh: '婴儿', grade: '1' },
  { en: 'grandpa', zh: '爷爷', grade: '1' },
  { en: 'grandma', zh: '奶奶', grade: '1' },
  { en: 'house', zh: '房子', grade: '1' },
  { en: 'home', zh: '家', grade: '1' },
  { en: 'love', zh: '爱', grade: '1' },
  { en: 'happy', zh: '开心的', grade: '1' },
  { en: 'big', zh: '大的', grade: '1' },
  { en: 'small', zh: '小的', grade: '1' },
  { en: 'my', zh: '我的', grade: '1' },
  { en: 'please', zh: '请', grade: '1' },
  { en: 'yes', zh: '是', grade: '1' },
  { en: 'no', zh: '不', grade: '1' },

  { en: 'play football', zh: '踢足球', grade: '2' },
  { en: 'fly a kite', zh: '放风筝', grade: '2' },
  { en: 'ride a bike', zh: '骑自行车', grade: '2' },
  { en: 'make a model plane', zh: '做飞机模型', grade: '2' },
  { en: 'swim', zh: '游泳', grade: '2' },
  { en: 'make a snowman', zh: '堆雪人', grade: '2' },
  { en: "can't", zh: '不能', grade: '2' },
  { en: 'rainy', zh: '下雨的', grade: '2' },
  { en: 'cloudy', zh: '多云的', grade: '2' },
  { en: 'snowy', zh: '下雪的', grade: '2' },
  { en: 'sunny', zh: '晴朗的', grade: '2' },
  { en: 'windy', zh: '多风的', grade: '2' },
  { en: 'umbrella', zh: '雨伞', grade: '2' },
  { en: 'weather', zh: '天气', grade: '2' },
  { en: 'wow', zh: '哇', grade: '2' },
  { en: "let's", zh: '让我们', grade: '2' },
  { en: 'spring', zh: '春天', grade: '2' },
  { en: 'summer', zh: '夏天', grade: '2' },
  { en: 'autumn', zh: '秋天', grade: '2' },
  { en: 'winter', zh: '冬天', grade: '2' },
  { en: 'hot', zh: '热的', grade: '2' },
  { en: 'warm', zh: '温暖的', grade: '2' },
  { en: 'cool', zh: '凉爽的', grade: '2' },
  { en: 'cold', zh: '冷的', grade: '2' },
  { en: 'favourite', zh: '特别喜爱的', grade: '2' },
  { en: 'season', zh: '季节', grade: '2' },
  { en: 'eleven', zh: '十一', grade: '2' },
  { en: 'twelve', zh: '十二', grade: '2' },
  { en: 'twenty', zh: '二十', grade: '2' },
  { en: 'thirty', zh: '三十', grade: '2' },
  { en: 'forty', zh: '四十', grade: '2' },
  { en: 'fifty', zh: '五十', grade: '2' },
  { en: 'thirteen', zh: '十三', grade: '2' },
  { en: 'fourteen', zh: '十四', grade: '2' },
  { en: 'fifteen', zh: '十五', grade: '2' },
  { en: 'time', zh: '时间', grade: '2' },
  { en: 'playtime', zh: '游戏时间', grade: '2' },
  { en: 'get up', zh: '起床', grade: '2' },
  { en: 'eat breakfast', zh: '吃早饭', grade: '2' },
  { en: 'go to school', zh: '去上学', grade: '2' },
  { en: 'eat lunch', zh: '吃午饭', grade: '2' },
  { en: 'go home', zh: '回家', grade: '2' },
  { en: 'eat dinner', zh: '吃晚饭', grade: '2' },
  { en: 'go to bed', zh: '上床睡觉', grade: '2' },
  { en: 'when', zh: '什么时候', grade: '2' },
  { en: 'every day', zh: '每天', grade: '2' },
  { en: 'at', zh: '在', grade: '2' },
  { en: 'Sunday', zh: '星期日', grade: '2' },
  { en: 'Monday', zh: '星期一', grade: '2' },
  { en: 'Tuesday', zh: '星期二', grade: '2' },
  { en: 'Wednesday', zh: '星期三', grade: '2' },
  { en: 'Thursday', zh: '星期四', grade: '2' },
  { en: 'Friday', zh: '星期五', grade: '2' },
  { en: 'Saturday', zh: '星期六', grade: '2' },
  { en: 'today', zh: '今天', grade: '2' },

  { en: 'pen', zh: '钢笔', grade: '3' },
  { en: 'pencil box', zh: '铅笔盒', grade: '3' },
  { en: 'ruler', zh: '尺子', grade: '3' },
  { en: 'eraser', zh: '橡皮', grade: '3' },
  { en: 'crayon', zh: '蜡笔', grade: '3' },
  { en: 'head', zh: '头', grade: '3' },
  { en: 'face', zh: '脸', grade: '3' },
  { en: 'nose', zh: '鼻子', grade: '3' },
  { en: 'mouth', zh: '嘴', grade: '3' },
  { en: 'eye', zh: '眼睛', grade: '3' },
  { en: 'ear', zh: '耳朵', grade: '3' },
  { en: 'arm', zh: '胳膊', grade: '3' },
  { en: 'hand', zh: '手', grade: '3' },
  { en: 'leg', zh: '腿', grade: '3' },
  { en: 'foot', zh: '脚', grade: '3' },
  { en: 'body', zh: '身体', grade: '3' },
  { en: 'red', zh: '红色的', grade: '3' },
  { en: 'yellow', zh: '黄色的', grade: '3' },
  { en: 'green', zh: '绿色的', grade: '3' },
  { en: 'blue', zh: '蓝色的', grade: '3' },
  { en: 'purple', zh: '紫色的', grade: '3' },
  { en: 'white', zh: '白色的', grade: '3' },
  { en: 'black', zh: '黑色的', grade: '3' },
  { en: 'orange', zh: '橙色的', grade: '3' },
  { en: 'brown', zh: '棕色的', grade: '3' },
  { en: 'cat', zh: '猫', grade: '3' },
  { en: 'dog', zh: '狗', grade: '3' },
  { en: 'monkey', zh: '猴子', grade: '3' },
  { en: 'panda', zh: '熊猫', grade: '3' },
  { en: 'rabbit', zh: '兔子', grade: '3' },
  { en: 'duck', zh: '鸭子', grade: '3' },
  { en: 'pig', zh: '猪', grade: '3' },
  { en: 'bird', zh: '鸟', grade: '3' },
  { en: 'bear', zh: '熊', grade: '3' },
  { en: 'elephant', zh: '大象', grade: '3' },
  { en: 'tiger', zh: '老虎', grade: '3' },
  { en: 'zebra', zh: '斑马', grade: '3' },
  { en: 'cake', zh: '蛋糕', grade: '3' },
  { en: 'bread', zh: '面包', grade: '3' },
  { en: 'juice', zh: '果汁', grade: '3' },
  { en: 'milk', zh: '牛奶', grade: '3' },
  { en: 'water', zh: '水', grade: '3' },
  { en: 'egg', zh: '蛋', grade: '3' },
  { en: 'fish', zh: '鱼', grade: '3' },
  { en: 'rice', zh: '米饭', grade: '3' },
  { en: 'one', zh: '一', grade: '3' },
  { en: 'two', zh: '二', grade: '3' },
  { en: 'three', zh: '三', grade: '3' },
  { en: 'four', zh: '四', grade: '3' },
  { en: 'five', zh: '五', grade: '3' },
  { en: 'six', zh: '六', grade: '3' },
  { en: 'seven', zh: '七', grade: '3' },
  { en: 'eight', zh: '八', grade: '3' },
  { en: 'nine', zh: '九', grade: '3' },
  { en: 'ten', zh: '十', grade: '3' },
  { en: 'UK', zh: '英国', grade: '3' },
  { en: 'Canada', zh: '加拿大', grade: '3' },
  { en: 'USA', zh: '美国', grade: '3' },
  { en: 'China', zh: '中国', grade: '3' },
  { en: 'she', zh: '她', grade: '3' },
  { en: 'he', zh: '他', grade: '3' },
  { en: 'boy', zh: '男孩', grade: '3' },
  { en: 'girl', zh: '女孩', grade: '3' },
  { en: 'new', zh: '新的', grade: '3' },
  { en: 'dad', zh: '爸爸', grade: '3' },
  { en: 'mom', zh: '妈妈', grade: '3' },
  { en: 'man', zh: '男人', grade: '3' },
  { en: 'woman', zh: '女人', grade: '3' },
  { en: 'grandmother', zh: '(外)祖母', grade: '3' },
  { en: 'grandfather', zh: '(外)祖父', grade: '3' },
  { en: 'thin', zh: '瘦的', grade: '3' },
  { en: 'fat', zh: '胖的', grade: '3' },
  { en: 'tall', zh: '高的', grade: '3' },
  { en: 'short', zh: '矮的', grade: '3' },
  { en: 'long', zh: '长的', grade: '3' },
  { en: 'giraffe', zh: '长颈鹿', grade: '3' },
  { en: 'on', zh: '在……上', grade: '3' },
  { en: 'in', zh: '在……里', grade: '3' },
  { en: 'under', zh: '在……下面', grade: '3' },
  { en: 'cap', zh: '帽子', grade: '3' },
  { en: 'ball', zh: '球', grade: '3' },
  { en: 'car', zh: '小汽车', grade: '3' },
  { en: 'boat', zh: '小船', grade: '3' },
  { en: 'map', zh: '地图', grade: '3' },
  { en: 'toy', zh: '玩具', grade: '3' },
  { en: 'box', zh: '盒', grade: '3' },
  { en: 'pear', zh: '梨', grade: '3' },
  { en: 'apple', zh: '苹果', grade: '3' },
  { en: 'banana', zh: '香蕉', grade: '3' },
  { en: 'strawberry', zh: '草莓', grade: '3' },
  { en: 'grape', zh: '葡萄', grade: '3' },
  { en: 'buy', zh: '买', grade: '3' },
  { en: 'fruit', zh: '水果', grade: '3' },
  { en: 'sixteen', zh: '十六', grade: '3' },
  { en: 'seventeen', zh: '十七', grade: '3' },
  { en: 'eighteen', zh: '十八', grade: '3' },
  { en: 'nineteen', zh: '十九', grade: '3' },
  { en: 'kite', zh: '风筝', grade: '3' },
  { en: 'beautiful', zh: '美丽的', grade: '3' },

  { en: 'classroom', zh: '教室', grade: '4' },
  { en: 'window', zh: '窗户', grade: '4' },
  { en: 'blackboard', zh: '黑板', grade: '4' },
  { en: 'light', zh: '电灯', grade: '4' },
  { en: 'picture', zh: '图画', grade: '4' },
  { en: 'door', zh: '门', grade: '4' },
  { en: "teacher's desk", zh: '讲台', grade: '4' },
  { en: 'computer', zh: '计算机', grade: '4' },
  { en: 'fan', zh: '风扇', grade: '4' },
  { en: 'wall', zh: '墙壁', grade: '4' },
  { en: 'floor', zh: '地板', grade: '4' },
  { en: 'really', zh: '真的', grade: '4' },
  { en: 'near', zh: '距离近', grade: '4' },
  { en: 'TV', zh: '电视', grade: '4' },
  { en: 'clean', zh: '打扫', grade: '4' },
  { en: 'help', zh: '帮助', grade: '4' },
  { en: 'schoolbag', zh: '书包', grade: '4' },
  { en: 'maths book', zh: '数学书', grade: '4' },
  { en: 'English book', zh: '英语书', grade: '4' },
  { en: 'Chinese book', zh: '语文书', grade: '4' },
  { en: 'storybook', zh: '故事书', grade: '4' },
  { en: 'candy', zh: '糖果', grade: '4' },
  { en: 'notebook', zh: '笔记本', grade: '4' },
  { en: 'key', zh: '钥匙', grade: '4' },
  { en: 'lost', zh: '丢失', grade: '4' },
  { en: 'so much', zh: '非常地', grade: '4' },
  { en: 'cute', zh: '可爱的', grade: '4' },
  { en: 'strong', zh: '强壮的', grade: '4' },
  { en: 'friendly', zh: '友好的', grade: '4' },
  { en: 'quiet', zh: '安静的', grade: '4' },
  { en: 'hair', zh: '头发', grade: '4' },
  { en: 'shoe', zh: '鞋', grade: '4' },
  { en: 'glasses', zh: '眼镜', grade: '4' },
  { en: 'his', zh: '他的', grade: '4' },
  { en: 'or', zh: '或者', grade: '4' },
  { en: 'right', zh: '正确的', grade: '4' },
  { en: 'hat', zh: '帽子', grade: '4' },
  { en: 'her', zh: '她的', grade: '4' },
  { en: 'bedroom', zh: '卧室', grade: '4' },
  { en: 'living room', zh: '客厅', grade: '4' },
  { en: 'study', zh: '书房', grade: '4' },
  { en: 'kitchen', zh: '厨房', grade: '4' },
  { en: 'bathroom', zh: '卫生间', grade: '4' },
  { en: 'bed', zh: '床', grade: '4' },
  { en: 'phone', zh: '电话', grade: '4' },
  { en: 'table', zh: '桌子', grade: '4' },
  { en: 'sofa', zh: '长沙发', grade: '4' },
  { en: 'fridge', zh: '冰箱', grade: '4' },
  { en: 'find', zh: '找到', grade: '4' },
  { en: 'them', zh: '他们', grade: '4' },
  { en: 'beef', zh: '牛肉', grade: '4' },
  { en: 'noodles', zh: '面条', grade: '4' },
  { en: 'soup', zh: '汤', grade: '4' },
  { en: 'vegetable', zh: '蔬菜', grade: '4' },
  { en: 'chicken', zh: '鸡肉', grade: '4' },
  { en: 'hungry', zh: '饥饿的', grade: '4' },
  { en: 'for', zh: '为', grade: '4' },
  { en: 'dinner', zh: '晚餐', grade: '4' },
  { en: 'wait', zh: '等待', grade: '4' },
  { en: 'parents', zh: '父母', grade: '4' },
  { en: 'cousin', zh: '堂/表兄弟/姐妹', grade: '4' },
  { en: 'uncle', zh: '叔/伯/舅/姑父/姨父', grade: '4' },
  { en: 'aunt', zh: '姑/姨/婶/伯母/舅母', grade: '4' },
  { en: 'baby brother', zh: '婴儿小弟弟', grade: '4' },
  { en: 'doctor', zh: '医生', grade: '4' },
  { en: 'cook', zh: '厨师', grade: '4' },
  { en: 'driver', zh: '司机', grade: '4' },
  { en: 'farmer', zh: '农民', grade: '4' },
  { en: 'nurse', zh: '护士', grade: '4' },
  { en: 'people', zh: '人们', grade: '4' },
  { en: 'but', zh: '但是', grade: '4' },
  { en: 'little', zh: '小的', grade: '4' },
  { en: 'puppy', zh: '小狗', grade: '4' },
  { en: 'job', zh: '工作', grade: '4' },
  { en: 'baseball player', zh: '棒球运动员', grade: '4' },
  { en: 'first floor', zh: '一楼', grade: '4' },
  { en: 'second floor', zh: '二楼', grade: '4' },
  { en: "teacher's office", zh: '教师办公室', grade: '4' },
  { en: 'library', zh: '图书馆', grade: '4' },
  { en: 'playground', zh: '操场', grade: '4' },
  { en: 'computer room', zh: '计算机房', grade: '4' },
  { en: 'art room', zh: '美术教室', grade: '4' },
  { en: 'music room', zh: '音乐教室', grade: '4' },
  { en: 'next to', zh: '紧邻', grade: '4' },
  { en: 'homework', zh: '作业', grade: '4' },
  { en: 'class', zh: '班级', grade: '4' },
  { en: 'way', zh: '方向', grade: '4' },
  { en: 'breakfast', zh: '早餐', grade: '4' },
  { en: 'English class', zh: '英语课', grade: '4' },
  { en: 'lunch', zh: '午餐', grade: '4' },
  { en: 'music class', zh: '音乐课', grade: '4' },
  { en: 'PE class', zh: '体育课', grade: '4' },
  { en: 'over', zh: '结束', grade: '4' },
  { en: 'now', zh: '现在', grade: '4' },
  { en: "o'clock", zh: '点钟', grade: '4' },
  { en: 'kid', zh: '小孩', grade: '4' },
  { en: 'hurry up', zh: '快点', grade: '4' },
  { en: 'come on', zh: '快', grade: '4' },
  { en: 'just a minute', zh: '稍等一会儿', grade: '4' },
  { en: 'outside', zh: '在户外', grade: '4' },
  { en: 'be careful', zh: '小心', grade: '4' },
  { en: 'New York', zh: '纽约', grade: '4' },
  { en: 'how about', zh: '怎么样', grade: '4' },
  { en: 'degree', zh: '度', grade: '4' },
  { en: 'world', zh: '世界', grade: '4' },
  { en: 'London', zh: '伦敦', grade: '4' },
  { en: 'Moscow', zh: '莫斯科', grade: '4' },
  { en: 'Singapore', zh: '新加坡', grade: '4' },
  { en: 'Sydney', zh: '悉尼', grade: '4' },
  { en: 'tomato', zh: '西红柿', grade: '4' },
  { en: 'potato', zh: '土豆', grade: '4' },
  { en: 'green beans', zh: '豆角', grade: '4' },
  { en: 'carrot', zh: '胡萝卜', grade: '4' },
  { en: 'horse', zh: '马', grade: '4' },
  { en: 'cow', zh: '母牛', grade: '4' },
  { en: 'sheep', zh: '羊', grade: '4' },
  { en: 'hen', zh: '母鸡', grade: '4' },
  { en: 'these', zh: '这些', grade: '4' },
  { en: 'yum', zh: '好吃', grade: '4' },
  { en: 'animal', zh: '动物', grade: '4' },
  { en: 'those', zh: '那些', grade: '4' },
  { en: 'garden', zh: '花园', grade: '4' },
  { en: 'farm', zh: '农场', grade: '4' },
  { en: 'goat', zh: '山羊', grade: '4' },
  { en: 'eat', zh: '吃', grade: '4' },
  { en: 'clothes', zh: '衣服', grade: '4' },
  { en: 'pants', zh: '裤子', grade: '4' },
  { en: 'dress', zh: '连衣裙', grade: '4' },
  { en: 'skirt', zh: '女裙', grade: '4' },
  { en: 'coat', zh: '外套', grade: '4' },
  { en: 'sweater', zh: '毛衣', grade: '4' },
  { en: 'sock', zh: '短袜', grade: '4' },
  { en: 'shorts', zh: '短裤', grade: '4' },
  { en: 'jacket', zh: '夹克衫', grade: '4' },
  { en: 'shirt', zh: '衬衫', grade: '4' },
  { en: 'yours', zh: '你的', grade: '4' },
  { en: 'whose', zh: '谁的', grade: '4' },
  { en: 'mine', zh: '我的', grade: '4' },
  { en: 'pack', zh: '收拾', grade: '4' },
  { en: 'glove', zh: '手套', grade: '4' },
  { en: 'scarf', zh: '围巾', grade: '4' },
  { en: 'sunglasses', zh: '太阳镜', grade: '4' },
  { en: 'pretty', zh: '美观的', grade: '4' },
  { en: 'expensive', zh: '昂贵的', grade: '4' },
  { en: 'cheap', zh: '便宜的', grade: '4' },
  { en: 'nice', zh: '好的', grade: '4' },
  { en: 'try on', zh: '试穿', grade: '4' },
  { en: 'size', zh: '尺码', grade: '4' },
  { en: 'of course', zh: '当然', grade: '4' },
  { en: 'too', zh: '太', grade: '4' },
  { en: 'just', zh: '正好', grade: '4' },
  { en: 'how much', zh: '多少钱', grade: '4' },
  { en: 'eighty', zh: '八十', grade: '4' },
  { en: 'dollar', zh: '美元', grade: '4' },

  { en: 'old', zh: '年老的', grade: '5' },
  { en: 'young', zh: '年轻的', grade: '5' },
  { en: 'funny', zh: '滑稽的', grade: '5' },
  { en: 'kind', zh: '体贴的', grade: '5' },
  { en: 'strict', zh: '严厉的', grade: '5' },
  { en: 'polite', zh: '有礼貌的', grade: '5' },
  { en: 'hard-working', zh: '工作努力的', grade: '5' },
  { en: 'helpful', zh: '有用的', grade: '5' },
  { en: 'clever', zh: '聪明的', grade: '5' },
  { en: 'shy', zh: '羞怯的', grade: '5' },
  { en: 'know', zh: '知道', grade: '5' },
  { en: 'our', zh: '我们的', grade: '5' },
  { en: 'Ms', zh: '女士', grade: '5' },
  { en: 'will', zh: '将要', grade: '5' },
  { en: 'sometimes', zh: '有时', grade: '5' },
  { en: 'robot', zh: '机器人', grade: '5' },
  { en: 'him', zh: '他', grade: '5' },
  { en: 'speak', zh: '说', grade: '5' },
  { en: 'finish', zh: '完成', grade: '5' },
  { en: 'weekend', zh: '周末', grade: '5' },
  { en: 'wash', zh: '洗', grade: '5' },
  { en: 'wash my clothes', zh: '洗我的衣服', grade: '5' },
  { en: 'watch TV', zh: '看电视', grade: '5' },
  { en: 'do homework', zh: '做作业', grade: '5' },
  { en: 'read books', zh: '看书', grade: '5' },
  { en: 'cooking', zh: '烹饪', grade: '5' },
  { en: 'often', zh: '经常', grade: '5' },
  { en: 'park', zh: '公园', grade: '5' },
  { en: 'tired', zh: '疲倦的', grade: '5' },
  { en: 'sport', zh: '体育运动', grade: '5' },
  { en: 'play sports', zh: '做运动', grade: '5' },
  { en: 'should', zh: '应该', grade: '5' },
  { en: 'every', zh: '每一个', grade: '5' },
  { en: 'day', zh: '一天', grade: '5' },
  { en: 'schedule', zh: '工作计划', grade: '5' },
  { en: 'sandwich', zh: '三明治', grade: '5' },
  { en: 'salad', zh: '沙拉', grade: '5' },
  { en: 'hamburger', zh: '汉堡包', grade: '5' },
  { en: 'ice cream', zh: '冰淇淋', grade: '5' },
  { en: 'tea', zh: '茶', grade: '5' },
  { en: 'fresh', zh: '新鲜的', grade: '5' },
  { en: 'healthy', zh: '健康的', grade: '5' },
  { en: 'delicious', zh: '美味的', grade: '5' },
  { en: 'hot', zh: '辣的', grade: '5' },
  { en: 'sweet', zh: '甜的', grade: '5' },
  { en: 'drink', zh: '喝', grade: '5' },
  { en: 'thirsty', zh: '口渴的', grade: '5' },
  { en: 'food', zh: '食物', grade: '5' },
  { en: 'onion', zh: '洋葱', grade: '5' },
  { en: 'sing', zh: '唱', grade: '5' },
  { en: 'song', zh: '歌曲', grade: '5' },
  { en: 'sing songs', zh: '唱歌', grade: '5' },
  { en: 'play the pipa', zh: '弹琵琶', grade: '5' },
  { en: 'Kung fu', zh: '功夫', grade: '5' },
  { en: 'do Kung fu', zh: '练功夫', grade: '5' },
  { en: 'dance', zh: '跳舞', grade: '5' },
  { en: 'draw', zh: '画', grade: '5' },
  { en: 'cartoon', zh: '漫画', grade: '5' },
  { en: 'draw cartoons', zh: '画漫画', grade: '5' },
  { en: 'play basketball', zh: '打篮球', grade: '5' },
  { en: 'play ping-pong', zh: '打乒乓球', grade: '5' },
  { en: 'speak English', zh: '说英语', grade: '5' },
  { en: "we'll", zh: '我们将', grade: '5' },
  { en: 'party', zh: '聚会', grade: '5' },
  { en: 'next', zh: '下一个', grade: '5' },
  { en: 'wonderful', zh: '极好的', grade: '5' },
  { en: 'learn', zh: '学', grade: '5' },
  { en: 'any', zh: '任何的', grade: '5' },
  { en: 'problem', zh: '问题', grade: '5' },
  { en: 'want', zh: '想要', grade: '5' },
  { en: 'send', zh: '发送', grade: '5' },
  { en: 'email', zh: '电子邮件', grade: '5' },
  { en: 'clock', zh: '点钟', grade: '5' },
  { en: 'do morning exercises', zh: '晨练', grade: '5' },
  { en: 'have English class', zh: '上英语课', grade: '5' },
  { en: 'evening', zh: '夜晚', grade: '5' },
  { en: 'usually', zh: '通常', grade: '5' },
  { en: 'noon', zh: '中午', grade: '5' },
  { en: 'climb mountains', zh: '爬山', grade: '5' },
  { en: 'go shopping', zh: '购物', grade: '5' },
  { en: 'play the piano', zh: '弹钢琴', grade: '5' },
  { en: 'visit grandparents', zh: '看望祖父母', grade: '5' },
  { en: 'go hiking', zh: '去远足', grade: '5' },
  { en: 'fall', zh: '秋天', grade: '5' },
  { en: 'which', zh: '哪一个', grade: '5' },
  { en: 'best', zh: '最', grade: '5' },
  { en: 'fly kites', zh: '放风筝', grade: '5' },
  { en: 'skate', zh: '滑冰', grade: '5' },
  { en: 'plant trees', zh: '种树', grade: '5' },
  { en: 'why', zh: '为什么', grade: '5' },
  { en: 'because', zh: '因为', grade: '5' },
  { en: 'sleep', zh: '睡觉', grade: '5' },

  { en: 'than', zh: '与…相比较', grade: '6' },
  { en: 'funnier', zh: '更滑稽的', grade: '6' },
  { en: 'heavy', zh: '重的', grade: '6' },
  { en: 'feet', zh: '脚', grade: '6' },
  { en: 'meter', zh: '米', grade: '6' },
  { en: 'ton', zh: '吨', grade: '6' },
  { en: 'each', zh: '各自', grade: '6' },
  { en: 'squid', zh: '鱿鱼', grade: '6' },
  { en: 'lobster', zh: '龙虾', grade: '6' },
  { en: 'shark', zh: '鲨鱼', grade: '6' },
  { en: 'deep', zh: '深的', grade: '6' },
  { en: 'seal', zh: '海豹', grade: '6' },
  { en: 'sperm', zh: '抹香鲸', grade: '6' },
  { en: 'killer whale', zh: '虎鲸', grade: '6' },
  { en: 'even', zh: '甚至', grade: '6' },
  { en: 'sore', zh: '疼的', grade: '6' },
  { en: 'feel', zh: '感觉', grade: '6' },
  { en: 'sick', zh: '不舒服的', grade: '6' },
  { en: 'hurt', zh: '疼痛', grade: '6' },
  { en: 'flu', zh: '流感', grade: '6' },
  { en: 'might', zh: '可以', grade: '6' },
  { en: 'worry', zh: '烦恼', grade: '6' },
  { en: 'medicine', zh: '药', grade: '6' },
  { en: 'stay', zh: '逗留', grade: '6' },
  { en: 'better', zh: '更好的', grade: '6' },
  { en: 'soon', zh: '立刻', grade: '6' },
  { en: 'fun', zh: '快乐', grade: '6' },
  { en: 'with', zh: '同…', grade: '6' },
  { en: 'reporter', zh: '记者', grade: '6' },
  { en: 'live', zh: '居住', grade: '6' },
  { en: 'teach', zh: '教', grade: '6' },
  { en: 'different', zh: '不同的', grade: '6' },
  { en: 'week', zh: '星期', grade: '6' },
  { en: 'say', zh: '说', grade: '6' },
  { en: 'excited', zh: '兴奋的', grade: '6' },
  { en: 'singer', zh: '歌手', grade: '6' },
  { en: 'actor', zh: '男演员', grade: '6' },
  { en: 'actress', zh: '女演员', grade: '6' },
  { en: 'artist', zh: '画家', grade: '6' },
  { en: 'Hong Kong', zh: '香港', grade: '6' },
  { en: 'engineer', zh: '工程师', grade: '6' },
  { en: 'company', zh: '公司', grade: '6' },
  { en: 'where', zh: '在哪里', grade: '6' },
  { en: 'work', zh: '工作', grade: '6' },
  { en: 'factory', zh: '工厂', grade: '6' },
  { en: 'design', zh: '设计', grade: '6' },
  { en: 'tip', zh: '小建议', grade: '6' },
  { en: 'money', zh: '钱', grade: '6' },
  { en: 'well', zh: '好', grade: '6' },
  { en: 'enjoy', zh: '享受', grade: '6' },
  { en: 'tourist', zh: '旅行者', grade: '6' },
  { en: 'police', zh: '警方', grade: '6' },
  { en: 'rain', zh: '雨', grade: '6' },
  { en: 'cloud', zh: '云', grade: '6' },
  { en: 'vapour', zh: '蒸汽', grade: '6' },
  { en: 'sun', zh: '太阳', grade: '6' },
  { en: 'stream', zh: '溪', grade: '6' },
  { en: 'shine', zh: '照耀', grade: '6' },
  { en: 'become', zh: '变成', grade: '6' },
  { en: 'drop', zh: '一滴', grade: '6' },
  { en: 'wake', zh: '醒来', grade: '6' },
  { en: 'think', zh: '想', grade: '6' },
  { en: 'meet', zh: '遇见', grade: '6' },
  { en: 'high', zh: '高的', grade: '6' },
  { en: 'other', zh: '其他的', grade: '6' },
  { en: 'fall', zh: '落下', grade: '6' },
  { en: 'down', zh: '向下', grade: '6' },
  { en: 'into', zh: '进入', grade: '6' },
  { en: 'come out', zh: '露出', grade: '6' },
  { en: 'again', zh: '又', grade: '6' },
  { en: 'seed', zh: '种子', grade: '6' },
  { en: 'soil', zh: '土壤', grade: '6' },
  { en: 'sprout', zh: '苗', grade: '6' },
  { en: 'plant', zh: '植物', grade: '6' },
  { en: 'then', zh: '然后', grade: '6' },
  { en: 'put', zh: '放', grade: '6' },
  { en: 'several', zh: '一些', grade: '6' },
  { en: 'see', zh: '看见', grade: '6' },
  { en: 'pot', zh: '锅', grade: '6' },
  { en: 'lovely', zh: '可爱的', grade: '6' },
  { en: 'make sure', zh: '核实', grade: '6' },
  { en: 'month', zh: '月份', grade: '6' },
  { en: 'still', zh: '仍然', grade: '6' },
  { en: 'hardly', zh: '几乎不', grade: '6' },
  { en: 'sad', zh: '悲伤的', grade: '6' },
  { en: 'angry', zh: '生气的', grade: '6' },
  { en: 'afraid', zh: '害怕的', grade: '6' },
  { en: 'worried', zh: '担心的', grade: '6' },
  { en: 'wear', zh: '穿', grade: '6' },
  { en: 'see a doctor', zh: '看医生', grade: '6' },
  { en: 'scientist', zh: '科学家', grade: '6' },
  { en: 'pilot', zh: '飞行员', grade: '6' },
  { en: 'coach', zh: '教练', grade: '6' },
  { en: 'fisherman', zh: '渔夫', grade: '6' },
  { en: 'secretary', zh: '秘书', grade: '6' },
  { en: 'businessman', zh: '商人', grade: '6' },
  { en: 'factory worker', zh: '工厂工人', grade: '6' },
  { en: 'postman', zh: '邮递员', grade: '6' },
  { en: 'hobby', zh: '爱好', grade: '6' },
  { en: 'dancing', zh: '跳舞', grade: '6' },
  { en: 'singing', zh: '唱歌', grade: '6' },
  { en: 'reading stories', zh: '读故事', grade: '6' },
  { en: 'playing football', zh: '踢足球', grade: '6' },
  { en: 'doing kung fu', zh: '练功夫', grade: '6' },
  { en: 'drawing cartoons', zh: '画漫画', grade: '6' },
  { en: 'go camping', zh: '去野营', grade: '6' },
  { en: 'go swimming', zh: '去游泳', grade: '6' },
  { en: 'take a trip', zh: '去旅行', grade: '6' },
  { en: 'see a film', zh: '看电影', grade: '6' },
  { en: 'study for a test', zh: '为考试学习', grade: '6' }
];

export default wordList;
